/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface:       'var(--color-surface)',
        ink:           'var(--color-ink)',
        muted:         'var(--color-muted)',
        sage:          'var(--color-sage)',
        'sage-light':  'var(--color-sage-light)',
        'sage-muted':  'var(--color-sage-muted)',
        terra:         'var(--color-terra-light)',
        'terra-cta':   'var(--color-terra-cta)',
        'border-warm': 'var(--color-border-warm)',
        primary: {
          50:  'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        error: {
          50:  'var(--color-error-50)',
          100: 'var(--color-error-100)',
          700: 'var(--color-error-700)',
        },
      },
      fontFamily: {
        display: ['Lora', 'Georgia', 'serif'],
        sans:    ['DM Sans', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        xs:    ['var(--text-xs)',   { lineHeight: 'var(--leading-xs)' }],
        sm:    ['var(--text-sm)',   { lineHeight: 'var(--leading-sm)' }],
        base:  ['var(--text-base)', { lineHeight: 'var(--leading-base)' }],
        lg:    ['var(--text-lg)',   { lineHeight: 'var(--leading-lg)' }],
        xl:    ['var(--text-xl)',   { lineHeight: 'var(--leading-xl)' }],
        '2xl': ['var(--text-2xl)', { lineHeight: 'var(--leading-2xl)' }],
        '3xl': ['var(--text-3xl)', { lineHeight: 'var(--leading-3xl)' }],
        '4xl': ['var(--text-4xl)', { lineHeight: 'var(--leading-4xl)' }],
      },
      borderRadius: {
        DEFAULT: '8px',
        sm:    '4px',
        md:    '8px',
        lg:    '12px',
        xl:    '16px',
        '2xl': '20px',
        full:  '9999px',
      },
      boxShadow: {
        card:     '0 1px 3px 0 rgba(28,25,23,0.06), 0 1px 2px -1px rgba(28,25,23,0.04)',
        elevated: '0 4px 12px 0 rgba(28,25,23,0.08), 0 2px 4px -1px rgba(28,25,23,0.04)',
        modal:    '0 16px 48px 0 rgba(28,25,23,0.12), 0 4px 12px -2px rgba(28,25,23,0.06)',
      },
    },
  },
  plugins: [],
}
