/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface:       'var(--color-surface)',
        ink:           'var(--color-ink)',
        muted:         'var(--color-muted)',
        sage:          'var(--color-sage)',
        'sage-light':  'var(--color-sage-light)',
        'sage-muted':  'var(--color-sage-muted)',
        terra:         'var(--color-terra-light)',
        'terra-cta':   'var(--color-terra-cta)',
        'border-warm': 'var(--color-border-warm)',
        primary: {
          50:  'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          950: 'var(--color-primary-950)',
        },
        error: {
          50:  'var(--color-error-50)',
          100: 'var(--color-error-100)',
          700: 'var(--color-error-700)',
        },
        success: {
          50:  'var(--color-success-50)',
          500: 'var(--color-success-500)',
          700: 'var(--color-success-700)',
        },
      },
      fontFamily: {
        display: ['Lora', 'Georgia', 'serif'],
        sans:    ['DM Sans', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        xs:    ['var(--text-xs)',   { lineHeight: 'var(--leading-xs)' }],
        sm:    ['var(--text-sm)',   { lineHeight: 'var(--leading-sm)' }],
        base:  ['var(--text-base)', { lineHeight: 'var(--leading-base)' }],
        lg:    ['var(--text-lg)',   { lineHeight: 'var(--leading-lg)' }],
        xl:    ['var(--text-xl)',   { lineHeight: 'var(--leading-xl)' }],
        '2xl': ['var(--text-2xl)', { lineHeight: 'var(--leading-2xl)' }],
        '3xl': ['var(--text-3xl)', { lineHeight: 'var(--leading-3xl)' }],
        '4xl': ['var(--text-4xl)', { lineHeight: 'var(--leading-4xl)' }],
        '5xl': ['var(--text-5xl)', { lineHeight: 'var(--leading-5xl)' }],
      },
      borderRadius: {
        DEFAULT: '8px',
        sm:    '4px',
        md:    '8px',
        lg:    '12px',
        xl:    '16px',
        '2xl': '20px',
        '3xl': '24px',
        full:  '9999px',
      },
      boxShadow: {
        card:     '0 1px 3px 0 rgba(28,25,23,0.06), 0 1px 2px -1px rgba(28,25,23,0.04)',
        elevated: '0 4px 12px 0 rgba(28,25,23,0.08), 0 2px 4px -1px rgba(28,25,23,0.04)',
        modal:    '0 25px 50px -12px rgba(28,25,23,0.15)',
        glass:    '0 8px 32px 0 rgba(28,25,23,0.06)',
        glow:     '0 8px 10px -6px rgba(196,131,90,0.2)',
      },
      width: {
        sidebar: '256px',
      },
      spacing: {
        sidebar: '256px',
      },
      backdropBlur: {
        glass: '12px',
      },
    },
  },
  plugins: [],
}
