import type { LeadCard, ProfileSummary } from './types'

export const MOCK_PROFILE: ProfileSummary = {
  name: 'Alex Chen',
  education: 'BSc Computer Science, University of Victoria (3rd year)',
  skills: ['Python', 'React', 'TypeScript', 'PostgreSQL', 'FastAPI', 'Git'],
  experience_summary:
    'Third-year CS student with backend and full-stack project experience. Built a habit-tracking app and contributed to an open-source CLI tool.',
  target_roles: ['Software Engineer Co-op', 'Backend Developer', 'Full-Stack Developer'],
  target_industries: ['SaaS', 'Fintech', 'Developer Tools'],
  locations: ['Victoria BC', 'Vancouver BC', 'Remote'],
  angles: [
    'First-gen student looking for co-op in Victoria BC',
    'Strong Python/FastAPI background pivoting to full-stack roles',
    'Open-source contributor interested in developer tooling',
    'Looking for companies that sponsor student developers',
  ],
  raw_input: {
    bio_text: 'Mock bio text',
    target_roles: ['Software Engineer Co-op'],
    target_industries: ['SaaS'],
    target_locations: ['Victoria BC'],
    interests: ['open source'],
  },
}

export const MOCK_CARDS: LeadCard[] = [
  {
    id: 'mock-1',
    lead_type: 'event',
    title: 'Victoria Tech Meetup — June Edition',
    subtitle: 'Monthly networking for local tech folks',
    why_relevant: 'Regular meetup in Victoria with a strong student presence. Past speakers have included engineers from local SaaS companies actively hiring co-ops.',
    source_urls: ['https://www.meetup.com/victoria-tech/'],
    action_plan: 'RSVP on Meetup.com and introduce yourself to the organizer beforehand via LinkedIn.',
    outreach_message: "Hi Sarah, I came across the Victoria Tech Meetup and noticed you organize it. I'm a third-year CS student at UVic looking for co-op opportunities in the local tech scene. I'd love to attend the June edition — is there anything I should know before coming?",
    date: '2026-06-15T18:00:00Z',
    location: 'Victoria BC',
    platform: 'in-person',
    confidence: 0.85,
  },
  {
    id: 'mock-2',
    lead_type: 'person',
    title: 'Jordan Liu',
    subtitle: 'Engineering Manager at Redbrick, Victoria BC',
    why_relevant: 'Jordan manages a backend team at Redbrick, a Victoria-based SaaS company known for hiring co-op students. They spoke at VictoriaJS last quarter about Python microservices.',
    source_urls: ['https://www.linkedin.com/in/jordanliu/'],
    action_plan: "Connect on LinkedIn with a personalized note referencing their Python microservices talk.",
    outreach_message: "Hi Jordan, I watched the recording of your VictoriaJS talk on Python microservices — the section on async task queues was really helpful for a FastAPI project I'm building. I'm a third-year CS student at UVic looking for a backend co-op in Victoria this summer. Would you be open to a 15-minute chat about what Redbrick looks for in co-op applicants?",
    location: 'Victoria BC',
    platform: 'linkedin',
    confidence: 0.78,
  },
  {
    id: 'mock-3',
    lead_type: 'community',
    title: 'YYJ Tech Slack',
    subtitle: 'Victoria\'s local tech community Slack workspace',
    why_relevant: 'The #jobs and #students channels in YYJ Tech are where local companies post co-op openings before they hit job boards. Several Victoria SaaS companies are active here.',
    source_urls: ['https://yyjtech.ca/'],
    action_plan: 'Join via yyjtech.ca, introduce yourself in #introductions, and monitor #jobs weekly.',
    outreach_message: null,
    location: 'Victoria BC (online)',
    platform: 'slack',
    confidence: 0.92,
  },
  {
    id: 'mock-4',
    lead_type: 'company',
    title: 'Redbrick',
    subtitle: 'Victoria-based SaaS — domain management platform',
    why_relevant: 'Redbrick is a Victoria SaaS company with a Python/TypeScript stack that matches your skills. They have an active co-op program and post openings on their careers page each January and August.',
    source_urls: ['https://redbrick.com/careers'],
    action_plan: "Apply directly through their careers page and mention YYJ Tech community in your cover letter. Their co-op applications open in August for the January term.",
    outreach_message: null,
    location: 'Victoria BC',
    platform: null,
    confidence: 0.88,
  },
  {
    id: 'mock-5',
    lead_type: 'resource',
    title: 'awesome-fastapi',
    subtitle: 'Curated list of FastAPI resources, tools, and projects',
    why_relevant: "Given your FastAPI background, this repo is a great way to discover open-source projects you could contribute to — contributions are a strong signal for backend co-op applications.",
    source_urls: ['https://github.com/mjhea0/awesome-fastapi'],
    action_plan: 'Browse the "Open Source Projects" section, find one with good first issues, and make a small contribution before applying to co-ops.',
    outreach_message: null,
    confidence: 0.72,
  },
]
